-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE NOT EXISTS (
    SELECT 1 
    FROM ITEM_TREE T2
    WHERE T2.PARENT_ITEM_ID = I.ITEM_ID
)
ORDER BY I.ITEM_ID DESC