SELECT 
    C.CAR_ID, 
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * (1-CH.DISCOUNT_RATE/100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (SELECT CAR_TYPE, DISCOUNT_RATE
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
      WHERE DURATION_TYPE = '30일 이상') AS CH
ON C.CAR_TYPE = CH.CAR_TYPE
WHERE CH.CAR_TYPE IN ('세단', 'SUV') 

AND C.CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
HAVING 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;