SELECT 
    U.USER_ID, 
    U.NICKNAME, 
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소',
    REGEXP_REPLACE(TLNO, '([0-9]{3})([0-9]{4})([0-9]{4})', '$1-$2-$3') AS '전화번호'
FROM USED_GOODS_USER U
JOIN USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY U.USER_ID DESC;