-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, sum(P.PRICE * O.AMOUNT) TOTAL_SALES
from FOOD_PRODUCT P, FOOD_ORDER O
where P.PRODUCT_ID = O.PRODUCT_ID
and to_char(PRODUCE_DATE, 'yyyy-mm') = '2022-05'
group by P.PRODUCT_ID, P.PRODUCT_NAME
order by TOTAL_SALES desc, P.PRODUCT_ID;