-- 코드를 입력하세요
SELECT
    H.HISTORY_ID,
    FLOOR((C.DAILY_FEE * (1-IFNULL(P.DISCOUNT_RATE, 0)/100) * H.RENTE_DATE)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN 
(
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS RENTE_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS H ON C.CAR_ID = H.CAR_ID 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON C.CAR_TYPE = P.CAR_TYPE AND
    P.DURATION_TYPE = (
        CASE
            WHEN H.RENTE_DATE >= 90 THEN '90일 이상'
            WHEN H.RENTE_DATE >= 30 THEN '30일 이상'
            WHEN H.RENTE_DATE >= 7 THEN '7일 이상'
        END
    )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;