WITH RECURSIVE num(HOUR) AS(
    SELECT 0
    UNION ALL
    SELECT HOUR+1 FROM num WHERE HOUR<23)

SELECT A.HOUR, IFNULL(B.COUNT, 0) AS COUNT
FROM NUM A
LEFT JOIN (
    SELECT HOUR(DATETIME) AS H, COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY H
) AS B ON A.HOUR = B.H
ORDER BY A.HOUR