-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM (
    SELECT BIT_OR(CODE) ALL_BIT
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
) AS SUB
JOIN DEVELOPERS D ON (SKILL_CODE & ALL_BIT) > 0
ORDER BY ID;