-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, sum(PRICE) TOTAL_SALES
from USED_GOODS_BOARD B, USED_GOODS_USER U
where B.WRITER_ID = U.USER_ID
and STATUS = 'DONE'
group by USER_ID, NICKNAME
having sum(PRICE) >= 700000
order by TOTAL_SALES;
