-- 코드를 입력하세요
SELECT 
    (SELECT MEMBER_NAME FROM MEMBER_PROFILE WHERE MEMBER_ID = R.MEMBER_ID) AS MEMBER_NAME,
    R.REVIEW_TEXT, 
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
WHERE MEMBER_ID = (
    SELECT R.MEMBER_ID
    FROM MEMBER_PROFILE M
    JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
    GROUP BY R.MEMBER_ID
    ORDER BY COUNT(R.MEMBER_ID) DESC
    LIMIT 1
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;