SELECT YEAR, YEAR_DEV, ID
FROM (
    SELECT 
        YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
        M.MAX_DEV - E.SIZE_OF_COLONY AS YEAR_DEV,
        E.ID
    FROM ECOLI_DATA E
    LEFT JOIN (
        SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_DEV
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) M
    ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
) AS sub
ORDER BY YEAR, YEAR_DEV, ID;