-- 코드를 작성해주세요
SELECT SUM(F.FISH_COUNT) AS FISH_COUNT
FROM (
    SELECT COUNT(I.FISH_TYPE) AS FISH_COUNT
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
    WHERE N.FISH_NAME IN ('BASS', 'SNAPPER')
    GROUP BY I.FISH_TYPE
) AS F